name: localsend
title: LocalSend
version: 0.1.0
summary: Share files to nearby devices.
description: Share files to nearby devices.
license: MIT

confinement: strict
base: core22
grade: devel

architectures:
  - build-on: amd64

slots:
  dbus-localsend:
    interface: dbus
    bus: session
    name: org.localsend.localsend_app
    
apps:
  localsend:
    command: bin/localsend
    extensions: [gnome]
    plugs:
    - network
    slots:
      - dbus-localsend

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter channel stable
      flutter upgrade
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  localsend:
    plugin: nil
    source: https://github.com/localsend/localsend.git
    after: [flutter-git]
    override-build: |
      set -eux
      flutter pub get
      flutter pub run build_runner build -d
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
      mv $CRAFT_PART_INSTALL/bin/localsend_app $CRAFT_PART_INSTALL/bin/localsend
